// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: meta.sql

package database

import (
	"context"
)

const setDatabaseUpdateTime = `-- name: SetDatabaseUpdateTime :one
UPDATE meta
SET last_update = (datetime(current_timestamp, 'localtime'))
RETURNING steam_id, last_update
`

func (q *Queries) SetDatabaseUpdateTime(ctx context.Context) (Meta, error) {
	row := q.db.QueryRowContext(ctx, setDatabaseUpdateTime)
	var i Meta
	err := row.Scan(&i.SteamID, &i.LastUpdate)
	return i, err
}
