// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: meta.sql

package database

import (
	"context"
	"database/sql"
)

const setDatabaseUpdateTime = `-- name: SetDatabaseUpdateTime :one
UPDATE meta
SET last_updated = (datetime(current_timestamp, 'localtime'))
RETURNING last_updated
`

func (q *Queries) SetDatabaseUpdateTime(ctx context.Context) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, setDatabaseUpdateTime)
	var last_updated sql.NullString
	err := row.Scan(&last_updated)
	return last_updated, err
}
