// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type SteamGame struct {
	Appid                  int64
	Name                   string
	PlaytimeForever        int64
	ImgIconUrl             string
	PlaytimeWindowsForever int64
	PlaytimeMacForever     int64
	PlaytimeLinuxForever   int64
	PlaytimeDeckForever    int64
	RtimeLastPlayed        int64
	PlaytimeDisconnected   int64
	Playtime2weeks         int64
}
