// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Meta struct {
	LastUpdated sql.NullString
}

type SteamGame struct {
	Appid                  int
	Name                   string
	PlaytimeForever        int
	ImgIconUrl             string
	PlaytimeWindowsForever int
	PlaytimeMacForever     int
	PlaytimeLinuxForever   int
	PlaytimeDeckForever    int
	RtimeLastPlayed        int
	PlaytimeDisconnected   int
	Playtime2weeks         int
}
